services:
  backend:
    build: ./backend   # Points to backend/Dockerfile
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend  # Points to frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend